CREATE TABLE `BILLING`(
	`ID` VARCHAR(36) NOT NULL,
	`PATIENT_ID` VARCHAR(36) DEFAULT NULL,
	`PHYSICIAN_ID` VARCHAR(36) DEFAULT NULL, 
	`BILLED_DATE` DATETIME DEFAULT NULL, 
	PRIMARY KEY (`ID`),
	FOREIGN KEY(`PHYSICIAN_ID`) REFERENCES `PHYSICIAN`(`ID`),
	FOREIGN KEY(`PATIENT_ID`) REFERENCES `PATIENT`(`ID`)
)