CREATE TABLE `HOLIDAY`(
	`NAME` VARCHAR(100) NOT NULL,
	`HOLIDAY_DATE` DATETIME DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL, 
	`MODIFIED_DATE` DATETIME DEFAULT NULL, 
	`CREATED_BY` VARCHAR(100) DEFAULT NULL, 
	`MODIFIED_BY` VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (`NAME`)
);