CREATE TABLE `PATIENT`(
	`ID` VARCHAR(36) NOT NULL,
	`NAME` VARCHAR(100) DEFAULT NULL,
	`AGE` INT DEFAULT NULL,
	`GENDER` VARCHAR(6) DEFAULT NULL,
	`CREATED_DATE` DATETIME DEFAULT NULL, 
	`MODIFIED_DATE` DATETIME DEFAULT NULL,
	`CREATED_BY` VARCHAR(100) DEFAULT NULL, 
	PRIMARY KEY (`ID`)
)